root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/app.exe cmd/main.go"
  bin = "tmp/app.exe"
  delay = 1000
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor", "testdata"]
  exclude_regex = ["_test.go"]
  stop_on_error = true

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
